### Pandas

In [1]:
import pandas

# Reading csv
dataframe = pandas.read_csv("cancer.csv", header=1)

# Converting dataframe to list
dataframe.values.tolist()[:2]

[['M',
  20.57,
  17.77,
  132.9,
  1326.0,
  0.08474,
  0.07864,
  0.0869,
  0.07017,
  0.1812,
  0.05667,
  0.5435,
  0.7339,
  3.398,
  74.08,
  0.005225,
  0.01308,
  0.0186,
  0.0134,
  0.01389,
  0.003532,
  24.99,
  23.41,
  158.8,
  1956.0,
  0.1238,
  0.1866,
  0.2416,
  0.186,
  0.275,
  0.08902],
 ['M',
  19.69,
  21.25,
  130.0,
  1203.0,
  0.1096,
  0.1599,
  0.1974,
  0.1279,
  0.2069,
  0.05999,
  0.7456,
  0.7869,
  4.585,
  94.03,
  0.00615,
  0.04006,
  0.03832,
  0.02058,
  0.0225,
  0.004571,
  23.57,
  25.53,
  152.5,
  1709.0,
  0.1444,
  0.4245,
  0.4504,
  0.243,
  0.3613,
  0.08758]]

In [3]:
dataframe

M  17.99  10.38   122.8    1001   0.1184   0.2776   0.3001   0.1471  \
0    M  20.57  17.77  132.90  1326.0  0.08474  0.07864  0.08690  0.07017   
1    M  19.69  21.25  130.00  1203.0  0.10960  0.15990  0.19740  0.12790   
2    M  11.42  20.38   77.58   386.1  0.14250  0.28390  0.24140  0.10520   
3    M  20.29  14.34  135.10  1297.0  0.10030  0.13280  0.19800  0.10430   
4    M  12.45  15.70   82.57   477.1  0.12780  0.17000  0.15780  0.08089   
..  ..    ...    ...     ...     ...      ...      ...      ...      ...   
563  M  21.56  22.39  142.00  1479.0  0.11100  0.11590  0.24390  0.13890   
564  M  20.13  28.25  131.20  1261.0  0.09780  0.10340  0.14400  0.09791   
565  M  16.60  28.08  108.30   858.1  0.08455  0.10230  0.09251  0.05302   
566  M  20.60  29.33  140.10  1265.0  0.11780  0.27700  0.35140  0.15200   
567  B   7.76  24.54   47.92   181.0  0.05263  0.04362  0.00000  0.00000   

     0.2419  ...   25.38  17.33   184.6    2019   0.1622   0.6656  0.7119  \
0    0.1812  ...  24.990  23.41  158.80  1956.0  0.12380  0.18660  0.2416   
1    0.2069  ...  23.570  25.53  152.50  1709.0  0.14440  0.42450  0.4504   
2    0.2597  ...  14.910  26.50   98.87   567.7  0.20980  0.86630  0.6869   
3    0.1809  ...  22.540  16.67  152.20  1575.0  0.13740  0.20500  0.4000   
4    0.2087  ...  15.470  23.75  103.40   741.6  0.17910  0.52490  0.5355   
..      ...  ...     ...    ...     ...     ...      ...      ...     ...   
563  0.1726  ...  25.450  26.40  166.10  2027.0  0.14100  0.21130  0.4107   
564  0.1752  ...  23.690  38.25  155.00  1731.0  0.11660  0.19220  0.3215   
565  0.1590  ...  18.980  34.12  126.70  1124.0  0.11390  0.30940  0.3403   
566  0.2397  ...  25.740  39.42  184.60  1821.0  0.16500  0.86810  0.9387   
567  0.1587  ...   9.456  30.37   59.16   268.6  0.08996  0.06444  0.0000   

     0.2654  0.4601   0.1189  
0    0.1860  0.2750  0.08902  
1    0.2430  0.3613  0.08758  
2    0.2575  0.6638  0.17300  
3    0.1625  0.2364  0.07678  
4    0.1741  0.3985  0.12440  
..      ...     ...      ...  
563  0.2216  0.2060  0.07115  
564  0.1628  0.2572  0.06637  
565  0.1418  0.2218  0.07820  
566  0.2650  0.4087  0.12400  
567  0.0000  0.2871  0.07039  

[568 rows x 31 columns]

### NumPy

In [4]:
import numpy as np

# Converting from and to list
vector = [1, 2, 3]
np_vector = np.array(vector)
vector = np_vector.tolist()
matrix = [[1, 2, 3], [4, 5, 6]]
np_matrix = np.array(matrix)
matrix = np_matrix.tolist()

In [5]:
# Elementwise operations
np_vector * np_vector
np_vector - np_vector
np_vector + np_vector
np_vector / np_vector
np_matrix * np_vector
np_matrix - np_vector
np_matrix + np_vector
np_matrix / np_vector

# Tensor operations
np_vector.dot(np_vector) # Production
np_matrix.T # Transpose

# Other operations
np.unique(np_vector)
np.argmax(np_matrix, axis=1)
np.min(np_matrix, axis=0)

array([1, 2, 3])

In [6]:
# Primitives
ones = np.ones((4, 3, 2))
zeros = np.zeros((2, 3, 4))
np_range = np.arange(1, 6)
np_range = np.arange(1, 6, 0.5)
np_linspace = np.linspace(0, 1, 4)
eye = np.eye(4)

In [5]:
# Shape
a = np.linspace(0, 1, 12)
a = a.reshape((2, 6))
a = a.reshape((-1, 3))

In [6]:
# Random
normal_distribution = np.random.randn(2, 3)
uniform_distribution = np.random.random((2, 3))
integers = np.random.randint(1, 3, (2, 3))

In [7]:
# Slicing
normal_distribution = np.random.randn(6, 8)

normal_distribution[1, 1]
normal_distribution[:, 1] 
normal_distribution[::-1, 1]
normal_distribution[1, :]

normal_distribution[normal_distribution > 0] # 1d!!!
normal_distribution[np.random.randn(6) > 0] # 2d!!!
normal_distribution[:, np.random.randn(8) > 0] # 2d!!!

ids = np.arange(0, 6, 2)
normal_distribution[ids]

array([[ 1.11290819,  0.53678883,  0.95677494, -0.58315618,  0.22064085,
        -0.56952053, -0.00634408,  0.93711405],
       [ 0.80664412,  0.36942141, -0.54610433,  0.45318784,  0.67904037,
         0.04522392, -0.24210308,  1.12616577],
       [ 0.07480189, -0.35458132,  0.44053341,  0.82149288,  1.58153533,
        -0.50471208,  1.19977057, -0.25837263]])

In [8]:
# Operations with slices
normal_distribution = np.random.randn(6, 4)
print(normal_distribution)
normal_distribution[:, 1] = 10
print(normal_distribution)

[[-0.54237926  0.58529465  1.21931899 -2.13545739]
 [ 0.10121346  0.88875159 -0.39884148 -0.31101041]
 [-1.15442655 -1.81404531 -1.3498683  -1.82264535]
 [-0.07890263 -0.56771651  0.7838692   0.30915667]
 [-0.32849365 -0.53898557 -1.97604693 -0.10050085]
 [-0.60153071 -1.01670092 -0.57882985 -1.67501161]]
[[-0.54237926 10.          1.21931899 -2.13545739]
 [ 0.10121346 10.         -0.39884148 -0.31101041]
 [-1.15442655 10.         -1.3498683  -1.82264535]
 [-0.07890263 10.          0.7838692   0.30915667]
 [-0.32849365 10.         -1.97604693 -0.10050085]
 [-0.60153071 10.         -0.57882985 -1.67501161]]
